import assert from 'node:assert/strict';
import {connect} from '../../packages/sdk/src/index.ts';
const game=await connect();
const layout=(await game.ui.snapshot()).data;
const surface=layout.nodes.find((n:any)=>n.surface.includes('Dialog_BillConfig'))?.surface;
assert.ok(surface);
const field=game.ui.locator({surface,role:'text_field',nth:0});
await field.fill('12');
assert.equal((await field.read()).data.valueText,'12');
await game.ui.locator({surface,role:'slider',source:'rp.slider'}).setValue(25);
assert.ok(Math.abs(Number((await game.ui.locator({surface,role:'slider',source:'rp.slider'}).read()).data.valueText)-25)<1);
await game.ui.locator({surface,role:'button',name:'Close'}).click();
const owner=(await game.state.bills()).data.items.find((i:any)=>i.bills.some((b:any)=>b.recipe==='CookMealSimple'));
const bill=owner.bills.find((b:any)=>b.recipe==='CookMealSimple');
const state=(await game.state.read(bill.reference,{fields:['repeatCount','ingredientSearchRadius','repeatMode']})).data;
assert.equal(state.fields.repeatCount,12); assert.ok(Math.abs(state.fields.ingredientSearchRadius-25)<1);
console.log(JSON.stringify(state,null,2));
await game.ui.locator({role:'button',name:'Do X times',ownerRef:owner.owner}).click();
console.log(JSON.stringify((await game.ui.snapshot()).data.nodes.filter((n:any)=>n.surface.includes('FloatMenu')&&n.actionable).map((n:any)=>({role:n.role,name:n.name})),null,2));
