import assert from 'node:assert/strict';
import {connect} from '../../packages/sdk/src/index.ts';
const game=await connect();
await game.ui.locator({role:'button',name:'Rice plant'}).click();
const root=()=>game.state.read('currentMap',{path:'zoneManager.allZones.0',fields:['ID','plantDefToGrow.defName','cells'],depth:1});
let state=(await root()).data.fields;
assert.equal(state['plantDefToGrow.defName'],'Plant_Rice'); assert.equal(state.cells.items.length,16);
await game.ui.action('designator.Designator_ZoneAdd_Growing_Expand').activate();
await game.map.drag(142,138,142,141);
await game.ui.press('Escape');
state=(await root()).data.fields; assert.equal(state.cells.items.length,20);
await game.map.click(139,139);
await game.ui.action('designator.Designator_ZoneDelete_Shrink').activate();
await game.map.drag(142,138,142,141);
await game.ui.press('Escape');
state=(await root()).data.fields; assert.equal(state.cells.items.length,16);
console.log('PASS actual UI growing zone 16→20→16 and Rice plant');
await game.runtime.save('rimUIMCP-Economy-Fixtures-Zones');
await game.ui.screenshot('rp-growing-zone-verified.png');
