import assert from 'node:assert/strict';
import {connect} from '../../packages/sdk/src/index.ts';
const game=await connect();
const findSurface=async()=> (await game.ui.snapshot()).data.nodes.find((n:any)=>n.name?.startsWith('Priority:'))?.surface;
const surface=await findSurface(); assert.ok(surface);
await game.ui.locator({surface,role:'checkbox',actionId:'filter.category.Foods'}).setChecked(false);
assert.equal((await game.ui.locator({surface,role:'checkbox',actionId:'filter.category.Foods'}).read()).data.isChecked,false);
await game.ui.locator({surface,role:'button',name:'Clear all'}).click();
await game.ui.locator({surface,role:'text_field'}).fill('steel');
await game.ui.locator({surface,role:'checkbox',actionId:'filter.thing.Steel'}).setChecked(true);
assert.equal((await game.ui.locator({surface,role:'checkbox',actionId:'filter.thing.Steel'}).read()).data.isChecked,true);
await game.ui.locator({surface,role:'text_field'}).fill('');
assert.equal((await game.ui.locator({surface,role:'text_field',source:'gui.text_field'}).read()).data.valueText,'');
await game.ui.locator({surface,role:'button',name:'Priority:',exact:false}).click();
console.log((await game.ui.snapshot()).data.nodes.filter((n:any)=>n.surface.includes('FloatMenu')&&n.actionable).map((n:any)=>({role:n.role,name:n.name})));
await game.ui.locator({role:'button',name:'Critical'}).click();
const state=await game.state.read('currentMap',{path:'zoneManager.allZones.1.settings',fields:['priorityInt']});
assert.equal(state.data.fields.priorityInt,'Critical');
console.log('PASS storage real UI category checkbox/search/Steel allow/empty fill/Critical priority');
await game.runtime.save('rimUIMCP-Economy-Verified');
await game.ui.screenshot('rp-storage-verified.png');
