import assert from 'node:assert/strict';
import { mkdirSync, writeFileSync } from 'node:fs';
import { connect, RimError } from '../packages/sdk/src/index.ts';
const game = await connect();
const directory = 'runs/input-acceptance-' + new Date().toISOString().replaceAll(':', '-'); mkdirSync(directory, { recursive: true });
const results: any[] = [];
await game.runtime.load('rimUIMCP-Economy-Verified');
await game.call('ui.reveal', { x: 146, z: 139 }); await game.map.click(146, 139);
await game.ui.locator({ role: 'button', name: 'Storage' }).click();
const search = game.ui.locator({ role: 'text_field', source: 'gui.text_field' });
await search.fill('Steel'); await search.press('A', 'ctrl'); await game.ui.press('Backspace');
assert.equal((await search.read()).data.valueText, ''); results.push({ case: 'visible text field focus + Ctrl+A + Backspace', passed: true });
await search.fill('Cloth'); await search.press('End'); await game.ui.press('Home', 'shift'); await game.ui.press('Backspace');
assert.equal((await search.read()).data.valueText, ''); results.push({ case: 'native Shift+Home text selection + deletion', passed: true });
await game.ui.panel('work').open();
await assert.rejects(game.ui.locator({ role: 'checkbox', name: 'Manual priorities' }).press('Space'), e => e instanceof RimError && e.code === 'UNSUPPORTED_INPUT');
results.push({ case: 'locator.press rejects non-text controls without clicking them', passed: true });
await game.runtime.load('rimUIMCP-Construction-Fixtures');
const before = (await game.state.query({ root: 'currentMap.blueprints', derived: false, fields: ['def.defName', 'thingIDNumber'], budgetMs: 500 })).data;
const blueprint = before.items.find((b: any) => b['def.defName'] === 'Blueprint_Wall'); assert.ok(blueprint);
await game.thing('Blueprint_Wall' + blueprint.thingIDNumber).select(); await game.ui.action('command.Designator_Cancel').activate();
const after = (await game.state.query({ root: 'currentMap.blueprints', derived: false, fields: ['thingIDNumber'], budgetMs: 500 })).data;
assert.equal(after.total, before.total - 1); assert.ok(!after.items.some((b: any) => b.thingIDNumber === blueprint.thingIDNumber));
results.push({ case: 'original Cancel gizmo removes the selected blueprint', passed: true, before: before.total, after: after.total });
writeFileSync(directory + '/results.json', JSON.stringify(results, null, 2)); console.log(JSON.stringify({ directory, results }, null, 2));
